### ISSUE TITLE
Crucibles no longer owned by a wallet still rendered as owned

### ISSUE THREAD

**Issue by thegostep** [alchemist-community/alchemist-frontend#12]
I am no longer the owner of the second crucible in this image (thegostep.eth)

<img width="638" alt="image" src="https://user-images.githubusercontent.com/15959632/110643719-667afd80-8182-11eb-8f07-3cb01c9e9c00.png">

**Comment by corollari** [comment]
Yeah, right now I use getLogs of Transfer events to display that but I'm not filtering them for previous owners, wanted to do this properly via a subgraph but might just hotfix it instead

**Comment by corollari** [comment]
Fixed but untested, @thegostep can you confirm that it works well?
