### ISSUE TITLE
add increase stake button for crucible

### ISSUE THREAD

**Issue by thegostep** [alchemist-community/alchemist-frontend#21]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/15959632/110708442-aebd0e80-81c8-11eb-8c49-17282ea0dfbe.png">

**Comment by corollari** [comment]
related to #3

**Comment by corollari** [comment]
gotta truncate those decimals as well

**Comment by pakaplace** [comment]
Working on this today with @nuurcodes

**Comment by nuurcodes** [comment]
Resolved here: alchemist-frontend@0b698a6
