### ISSUE TITLE
some users reported they are unable to see crucible when using metamask/trustwallet on mobile

### ISSUE THREAD

**Issue by sal-ash** [alchemist-community/alchemist-frontend#43]

**Comment by sal-ash** [comment]
![image](https://user-images.githubusercontent.com/44524714/112055450-c5f7e680-8b4e-11eb-9471-7cf44687a031.png)

**Comment by corollari** [comment]
btw, that last bug is not related to mobile

**Comment by sal-ash** [comment]
yeah when it was first reported the guy was using mobile so I assumed that was the issue
