### ISSUE TITLE
Fix Discord Link in Footer

### ISSUE THREAD

**Issue by Sheikh-A** [alchemist-community/alchemist-frontend#8]
Link should be: http://discord.alchemist.wtf/ 

See: https://github.com/alchemistcoin/alchemist

Voting: https://cast.alchemist.wtf/
Discord: http://discord.alchemist.wtf/
FAQ: https://hackmd.io/@thegostep/⚗️

Not: https://discord.alchemist.wtf/

Current link times out and throws error.

**Comment by corollari** [comment]
Thanks!

Just fixed it
